yemek/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yemek.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yeme20 : DbContext
    {
        public yeme20()
            : base("name=yeme20")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kullanıcılar> kullanıcılar { get; set; }
        public virtual DbSet<yemn> yemn { get; set; }
    }
}

yemek/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\lenovo\source\repos\yemek\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

yemek/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

yemek/Models/kullanıcılar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanıcılar
    {
        public int id { get; set; }
        public string kad { get; set; }
        public string sifre { get; set; }
    }
}

yemek/Models/yemn.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yemek.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    
    public partial class yemn
    {
        public int id { get; set; }
        public string foto { get; set; }
        
        public virtual HttpPostedFileBase fotoFile { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
    }
}

yemek/Areas/admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using yemek.Models;
using System.Web.Security;

namespace yemek.Areas.admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: admin/Login
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Alogin(kullanıcılar kull)
        {   
            using(yeme20 db= new yeme20())
            {
                var kullanıcıv = db.kullanıcılar.FirstOrDefault(
                    x => x.kad == kull.kad && x.sifre == kull.sifre);
                
                if(kullanıcıv !=null)
                {
                    FormsAuthentication.SetAuthCookie(kullanıcıv.kad, false);
                    return RedirectToAction("/index", "urunler");
                }

                return View("index");
                
            }
      
        }

    }
}

yemek/Areas/admin/Controllers/UrunlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using yemek.Models;
using System.IO;
using yemek.App_Code;




namespace yemek.Areas.admin.Controllers
{
    [Authorize]
    public class UrunlerController : Controller
    {
        // GET: admin/Urunler
        public ActionResult Index()
        {
            using (yeme20 db = new yeme20())
            {
                var model = db.yemn.ToList();
                return View(model);
            }

        }

        public ActionResult Yeni()
        {
            var model = new yemn();

            return View("UrunForm", model);
        }
        public ActionResult Guncelle(int id)
        {
            using (yeme20 db = new yeme20())
            {
                var model = db.yemn.Find(id);
                if (model == null)
                {
                    return HttpNotFound();
                }
                return View("UrunForm", model);
            }
        }
        public ActionResult Kaydet(yemn gelenyem)
        {
            using (yeme20 db = new yeme20())
            {
                if (gelenyem.id == 0)
                {

                    string fotoAdi = Seo.DosyaAdiDuzenle(gelenyem.fotoFile.FileName);
                    gelenyem.foto = fotoAdi;
                    db.yemn.Add(gelenyem);
                    gelenyem.fotoFile.SaveAs(Path.Combine(Server.MapPath("~/Content/images"), Path.GetFileName(fotoAdi)));

                }
                else
                {
                    var gg = db.yemn.Find(gelenyem.id);
                    if (gelenyem.fotoFile != null)
                    {
                        string fotoAdi = Seo.DosyaAdiDuzenle(gelenyem.fotoFile.FileName);
                        gelenyem.foto = fotoAdi;
                        gelenyem.fotoFile.SaveAs(Path.Combine(Server.MapPath("~/Content/images"), Path.GetFileName(fotoAdi)));

                    }
                    db.Entry(gg).CurrentValues.SetValues(gelenyem);

                }
                db.SaveChanges();
                return RedirectToAction("index");

            }

        }
        public ActionResult Sil(int id)
        {
            using (yeme20 db = new yeme20())
            {
                var silinecek = db.yemn.Find(id);
                db.yemn.Remove(silinecek);
                db.SaveChanges();
                return RedirectToAction("/index");
            }

        }
    }
}

yemek/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using yemek.Models;
namespace yemek.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {   
            using(yeme20 db = new yeme20())
            {
                var model = db.yemn.ToList();
                return View(model);
            }
            
        }
    }
}

yemek/Areas/admin/Views/Login/Index.cshtml
@model yemek.Models.kullanıcılar
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Log in</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/admin/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/Content/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/admin/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
      
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
               

                @using (Html.BeginForm("Alogin", "login",new { FormMethod.Post})){

                    <div class="input-group mb-3">
                        
                     @Html.TextBoxFor(m=>m.kad ,new { @class ="form-control",placeholder="Kullanıcı Adın",autofocus="auto"})   
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                
                    <div class="input-group mb-3">
                        
                    @Html.PasswordFor(m => m.sifre, new { @class = "form-control", placeholder = "Şifre", autofocus = "auto" })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                
                    <div class="row">
                       
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Giriş</button>
                        </div>
                        <!-- /.col -->
                    </div>
                }

                
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Content/admin/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/admin/dist/js/adminlte.min.js"></script>
</body>
</html>

yemek/Areas/admin/Views/Urunler/Index.cshtml
@model List<yemek.Models.yemn>
@using yemek.App_Code
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yemek</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Dashbord</a></li>
                        <li class="breadcrumb-item active">Yemek</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                   
                    <!-- /.card -->

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Yemekler ve içerikleri</h3>
                        </div>
                        <div>
                        <br />
                            @Html.ActionLink("Yeni Ürün Ekle", "Yeni", null, new { @class = "btn btn-primary mx-3" })
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Foto</th>
                                        <th>Başlık</th>
                                        <th>İçerik</th>
                                        <th>Güncelle</th>
                                        <th>Sil</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var yemm in Model)
                                    {
                                    <tr>
                                        <td><img src="~/Content/images/@yemm.foto" width="150"</td>
                                        <td>
                                            @yemm.baslik
                                        </td>
                                        <td> @Html.Raw(yemm.icerik)</td>
                                        <td>
                                            @Html.ActionLink("Güncelle","Guncelle",new { yemm.id }, new { @class="btn btn-info mx-4"})
                                        </td>
                                        <td>
                                            @Html.ActionLink("Sil", "Sil", new { yemm.id }, new { @class = "btn btn-danger mx-4" })
                                        </td>
                                    </tr>
                                    }
                                </tbody>   
                                <tfoot>
                                    <tr>
                                        <th>Foto</th>
                                        <th>Başlık</th>
                                        <th>İçerik</th>
                                        <th>Güncelle</th>
                                        <th>Sil</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

yemek/Areas/admin/Views/Urunler/UrunForm.cshtml
@model yemek.Models.yemn
@{
    ViewBag.Title = "UrunForm";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="container">
        <h2>Yemek Form Sayfası</h2>
        @using (Html.BeginForm("Kaydet", "Urunler", FormMethod.Post, new { @enctype="multipart/form-data"}))
        {
    <table class="table table-bordered">
        <tr>
            <td>
                Foto
            </td>
            <td>
                @if (Model.foto != null)
                {
                    <img src="~/Content/img/@Model.foto" width="250" />
                }
                @Html.TextBoxFor(m => m.fotoFile, new { type = "file" })
            </td>
        </tr>
        <tr>
            <td>
                Başlık
            </td>
            <td>
                @Html.TextBoxFor(m => m.baslik, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>
                İçerik
            </td>
            <td>
                @Html.TextBoxFor(m => m.icerik, new { @class = "form-control" })
            </td>
        </tr>
         <tr>
             <td>

             </td>
             <td>
                 @Html.HiddenFor(m=>m.foto)
                 @Html.HiddenFor(m=>m.id)
                 <input type="submit" value="Kaydet" class="btn btn-primary" />
             </td>
         </tr>
        
    </table> 
        }
    </div>

</div>

yemek/Views/Default/Index.cshtml
@model List<yemek.Models.yemn> 
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="slider">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block wow fadeInUp" data-wow-duration="500ms" data-wow-delay="300ms">
                    <div class="title">
                        <h3>Örnek <span>Tariflerinin Fotografları</span></h3>
                    </div>
                    <div id="owl-example" class="owl-carousel">
                        @foreach (var yemek in Model)
                        {
                        <div>
                            <img class="img-responsive" src="~/Content/images/@yemek.foto" alt="" width="150"height="175">
                        </div>
                        }


                    </div>
                </div>
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .container close -->
</section><!-- slider close -->
<!--
about-us start
============================== -->
<section id="about-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <img class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="400ms" src="~/Content/images/cooker-img.png" alt="cooker-img">
                    <h1 class="heading wow fadeInUp" data-wow-duration="400ms" data-wow-delay="500ms">
                        Can <span>Şefin</span> </br>Yemek  <span>Tarifleri</span>
                    </h1>
                    <p class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="600ms">
                        1971'de İstanbul, Kadıköy'de dünyaya gelen Can Bayraktar, 1996 yılına kadar Türkiye'de kaldı. Türkiye'de uzun yıllar annesi ile birlikte çalışan usta şef'in annesi restoran ve bar işletmeciliği yapmıştır.

                        25 yaşında iken 1995 senesinde Yüksek Lisans yapmak için Avustralya'ya gitmiştir. Bilkent Üniversitesi Turizm ve Otelcilik bölümünden mezun olmuş, daha sonra master yapmıştır.

                        Can Bayraktar, Sydney'de kuzeni ile birlikte 'Efendy' isimli bir Türk restoranı açmıştır. Menüsünde pek çok türk lezzeti bulunan restoran yurt dışında Türk lezzetlerini temsil eden bir marka haline gelmiştir.
                    </p>
                </div>
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .containe close -->
</section><!-- #call-to-action close -->
<!--
blog start
============================ -->



<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h1 class="heading">Yemek <span>Tarifleri</span> Can <span>Şeften</span></h1>
                    <ul>
                        @foreach (var yemek in Model)
                        { <li class="wow fadeInLeft" data-wow-duration="300ms" data-wow-delay="300ms">
                                <div class="blog-img">
                                    <img src="~/Content/images/@yemek.foto" alt="blog-img" width="200"height="175" >
                                </div>
                                <div class="content-right">
                                    <h3>@yemek.baslik</h3>
                                    @Html.Raw(@yemek.icerik)
                                </div>
                            </li>
                        }
                    </ul>
                    
                </div>
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .containe close -->
</section><!-- #blog close -->

<!--
    

price start
============================ -->
<section id="price">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h1 class="heading wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">Can <span>Şeften</span> Ufak <span>Tüyolar</span></h1>
                    <p class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="400ms">Soğan doğrarken gözlerinizin yaşarmaması için yanınızda bir mum yakın ve daha sonra söndürün. Başka bir yol ise soğanı ikiye bölün, soğuk su altında tutun, biraz dinlendirin ve sonra kesin.Eğer domatesleri doğrarken sürekli suyunu salmalarından şikayet ediyorsanız, domatesleri ekmek bıçağıyla kesin. Böylece halkaları daha ince olur ve suyu mutfağın her yerine dağılmaz. Dilimlenmiş patateslerin daha lezzetli olmasını istiyorsanız, üzerine bir tel ızgara yerleştirin ve tavuk butlarını dizin. Böylece tavuğun lezzeti ile patateslerin tadı çok daha güzel olur.Eğer tavuk şiş hazırlayacaksanız ve fırın kabınız istediğiniz büyüklükte değilse bunu kolaylaştıracak bir yöntemi sizinle paylaşıyoruz. Tavukları dikey olarak tutmak için tahta şişler kullanarak orta büyüklükteki bir fırın kabına sığdırabilirsiniz. </p>
                    <div class="pricing-list">
                        <div class="title">
                            <h3>Tarif <span>Listesi</span></h3>
                        </div>
                        <ul>
                            @foreach (var yemek in Model)
                            { 
                            <li class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                                <div class="item">
                                    <div class="item-title">
                                        <h2>@yemek.baslik</h2>
                                        <div class="border-bottom"></div>

                                    </div>
                                    @Html.Raw(@yemek.icerik)
                                </div>
                            </li>
                            }

                        </ul>
                        
                    </div>
                </div>
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .containe close -->
</section><!-- #price close -->
<!--
subscribe start
============================ -->

yemek/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Restaurant One Page HTML5 Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS
    ================================================ -->
    <!-- Owl Carousel -->
    <link rel="stylesheet" href="~/Content/css/owl.carousel.css">
    <!-- bootstrap.min css -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <!-- Font-awesome.min css -->
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css">
    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="~/Content/css/animate.min.css">

    <link rel="stylesheet" href="~/Content/css/main.css">
    <!-- Responsive Stylesheet -->
    <link rel="stylesheet" href="~/Content/css/responsive.css">
    <!-- Js -->
    <script src="~/Content/js/vendor/modernizr-2.6.2.min.js"></script>
    <!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> -->
    <script>window.jQuery || document.write('<script src="/Content/js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
    <script src="~/Content/js/jquery.nav.js"></script>
    <script src="~/Content/js/jquery.sticky.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/plugins.js"></script>
    <script src="~/Content/js/wow.min.js"></script>
    <script src="~/Content/js/main.js"></script>
</head>
<body>
    <!--
    header-img start
    ============================== -->
    <section id="hero-area">
        <img class="img-responsive" src="~/Content/images/header.jpg" alt="">
    </section>
    <!--
    Header start
    ============================== -->
    <nav id="navigation">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="block">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                   

                                </div>

                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <ul class="nav navbar-nav navbar-right" id="top-nav">
                                        <li><a href="#hero-area">Anasayfa</a></li>
                                        <li><a href="#about-us">Hakkımızda</a></li>
                                        <li><a href="#blog">Tarif</a></li>
                                        
                                        
                                        <li><a href="#contact-us">Iletişim</a></li>
                                    </ul>
                                </div><!-- /.navbar-collapse -->
                            </div><!-- /.container-fluid -->
                        </nav>
                    </div>
                </div><!-- .col-md-12 close -->
            </div><!-- .row close -->
        </div><!-- .container close -->
    </nav><!-- header close -->
    @RenderBody()
    <!--
    Slider start
    ============================== -->
    <!-- #contact-us close -->
    <!--
    footer  start
    ============================= -->
    <section id="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="block wow fadeInLeft" data-wow-delay="200ms">
                        <h3>ILETISIM <span>BILGILERI</span></h3>
                        <div class="info">
                            <ul>
                                <li>
                                    <h4><i class="fa fa-phone"></i>Telefon</h4>
                                    <p>(000) 123 456 78- (000) 123 4567 89</p>

                                </li>
                                <li>
                                    <h4><i class="fa fa-map-marker"></i>Adres</h4>
                                    <p>2120. Sokak Cengiz Mahallesi Çankaya/Ankara</p>
                                </li>
                                <li>
                                    <h4><i class="fa fa-envelope"></i>E mail</h4>
                                    <p>can.sef@gmail.com - can_seff2@mail.ru</p>

                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- .col-md-4 close -->
                
                <!-- .col-md-4 close -->
                <div class="col-md-4">
                    <div class="block wow fadeInLeft" data-wow-delay="1100ms">
                        <div class="gallary">
                            <h3>FOTO <span>YAYINI</span></h3>
                            <ul>
                                @foreach (var yemek in Model)
                                {
                                <li>
                                    <a href="#"><img src="~/Content/images/@yemek.foto" alt=""width="150"></a>
                                </li>
                                }
                                
                            </ul>
                        </div>
                        <div class="social-media-link">
                            <h3>Takip <span>Edin</span></h3>
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-dribbble"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-behance"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- .col-md-4 close -->
            </div><!-- .row close -->
        </div><!-- .containe close -->
    </section><!-- #footer close -->
    <!--
    footer-bottom  start
    ============================= -->
    
</body>
</html>